scrape_configs:
  - job_name: 'ping1'
    scrape_interval: 10s
    metrics_path: '/ping'
    scheme: 'http'
    params:
        host: ['vrashke.net','anykeyadmin.info','optina.ru','monvestnik.ru','192.168.0.30','192.168.0.31','192.168.0.105','192.168.0.101']
    static_configs:
      - targets: ['192.168.0.31:1000','192.168.0.30:3000'] # hosts where you start nax_exporter

  # проверка доступности сайтов
  - job_name: 'sites_mixa'
    scrape_interval: 60s
    metrics_path: '/metricsget'
    scheme: 'http'
    params:
        threads: ['1','2'] # threads - сколько функций будет выполняться одновременно, сколько урл будет проверяться одновременно default[8,8]
        fnc: ['check_url'] # fnc - список функций
        url: ['http://vrashke.ru','http://vrashke.net','http://anykeyadmin.info']  # url - список параметров-урл, - все параметры будут передаваться во все функции

        # регулярные выражения применяются только в функции 'check_url' и проверяются все урл
        # re_success - body урл должна соответствовать всем регулярным выражениям для успешной проверки
        # re_fail - body урл должна соответствовать хотябы одному регулярному выражению для неудачи
        re_success: ['mixamarciv','<nav']
        re_fail: []
        re_status_success: []
        re_status_fail: []
    static_configs:
        - targets: ['192.168.0.31:1000']  # targets - хосты на которых работает nax_exporter


  - job_name: 'rig1'
    scrape_interval: 10s
    metrics_path: '/httpget'
    scheme: 'http'
    params:
        url: ['http://192.168.0.101:3333']
        type: ['ethminer']
    static_configs:
      - targets: ['192.168.0.31:1000'] 


  - job_name: 'rig2'
    scrape_interval: 10s
    metrics_path: '/httpget'
    scheme: 'http'
    params:
        url: ['http://192.168.0.105:3333']
        type: ['ethminer']
    static_configs:
      - targets: ['192.168.0.31:1000'] 


  - job_name: 'balance_coinminepl'
    scrape_interval: 10s
    metrics_path: '/httpget'
    scheme: 'http'
    params:
        url: ['https://www2.coinmine.pl/eth/index.php?page=api%26api_key=11111%26id=11111%26action=getuserbalance']
        type: ['balance_coinminepl']
    static_configs:
      - targets: ['192.168.0.31:1000'] 



